// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCQZiAbbj9aHWLBekBETLFv56LJBy7Bo',
    appId: '1:279561786920:web:13d82fb11b275e901a871d',
    messagingSenderId: '279561786920',
    projectId: 'study-group-app-7f6fb',
    authDomain: 'study-group-app-7f6fb.firebaseapp.com',
    storageBucket: 'study-group-app-7f6fb.firebasestorage.app',
    measurementId: 'G-4Y1YCVEN2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtmb6YhS_IsBhKM3covhWZrPp6Ao4NUK4',
    appId: '1:279561786920:android:0553375f3736901f1a871d',
    messagingSenderId: '279561786920',
    projectId: 'study-group-app-7f6fb',
    storageBucket: 'study-group-app-7f6fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzSAKBHUsv88kvEwN_Ej3ZuaMPouFSIp8',
    appId: '1:279561786920:ios:2f862692736a1e0f1a871d',
    messagingSenderId: '279561786920',
    projectId: 'study-group-app-7f6fb',
    storageBucket: 'study-group-app-7f6fb.firebasestorage.app',
    iosBundleId: 'com.example.studyGroupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzSAKBHUsv88kvEwN_Ej3ZuaMPouFSIp8',
    appId: '1:279561786920:ios:2f862692736a1e0f1a871d',
    messagingSenderId: '279561786920',
    projectId: 'study-group-app-7f6fb',
    storageBucket: 'study-group-app-7f6fb.firebasestorage.app',
    iosBundleId: 'com.example.studyGroupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmCQZiAbbj9aHWLBekBETLFv56LJBy7Bo',
    appId: '1:279561786920:web:7c2d8a877f7da3461a871d',
    messagingSenderId: '279561786920',
    projectId: 'study-group-app-7f6fb',
    authDomain: 'study-group-app-7f6fb.firebaseapp.com',
    storageBucket: 'study-group-app-7f6fb.firebasestorage.app',
    measurementId: 'G-NPG7S5M2S4',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAmCQZiAbbj9aHWLBekBETLFv56LJBy7Bo',
    appId: '1:279561786920:web:13d82fb11b275e901a871d',
    messagingSenderId: '279561786920',
    projectId: 'study-group-app-7f6fb',
    authDomain: 'study-group-app-7f6fb.firebaseapp.com',
    storageBucket: 'study-group-app-7f6fb.firebasestorage.app',
    measurementId: 'G-4Y1YCVEN2H',
  );
}